name: Main

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test
        run: echo start
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.TEST_SECRET }}
          body: aaa
          files: AIoTIDESetup.exe
      - name: test
        run: echo end
